---

- hosts: all
  remote_user: client
  become: yes
  become_method: sudo
  vars_files:
   - ../vars/apache_vars.yml

  tasks:
  - name: Installing apache on ubuntu
    apt:
      name: apache2
      state: present
    when:
      ansible_os_family == "Debian"
  - name: Starting apache on ubuntu
    service:
      name: apache2
      state: started
    when:
      ansible_os_family == "Debian"
  - name: Copying configuration files
    template:
      src: ../files/ports.j2
      dest: /etc/apache2/ports.conf
    notify:
    - restart apache on ubuntu
    when:
      ansible_os_family == "Debian"
  - name: Install php on ubuntu
    apt: 
      name: php7.0
      state: present
    notify:
    - restart apache on ubuntu
    when:
      ansible_os_family == "Debian"

  - name: Installing apache on centos
    yum:
      name: httpd
      state: present
    when:
      ansible_os_family == "RedHat"
  - name: Starting apache on centos
    service:
      name: httpd
      state: started
    when:
      ansible_os_family == "RedHat"
  - template:
      src: ../files/httpd.j2
      dest: /etc/httpd/conf/httpd.conf
    notify:
    - restart apache on centos
    when:
      ansible_os_family == "RedHat"
  - name: Install php on centos
    yum: 
      name: php
      state: present
    notify:
    - restart apache on centos
    when:
      ansible_os_family == "RedHat"

  handlers:
    - name: restart apache on centos
      service:
        name: httpd
        state: restarted
    - name: restart apache on ubuntu
      service:
        name: apache2
        state: restarted
