---

- hosts: all
  remote_user: client
  become: yes
  become_method: sudo
  vars_files:
    - ../vars/mysql_vars.yml

  tasks:
    - name: Create apt repo
      shell: apt-key adv --keyserver pgp.mit.edu --recv-keys 5072E1F5 && echo "deb http://repo.mysql.com/apt/ubuntu/ trusty mysql-5.7" > /etc/apt/sources.list.d/mysql.list
      when:
        ansible_os_family == "Debian"
    - name: Update apt
      apt:
        update_cache: yes
      when:
        ansible_os_family == "Debian"
    - name: Install MySQL
      apt:
        name: mysql-server
        state: present
      when:
        ansible_os_family == "Debian"
    - name: Start mysql
      service:
        name=mysql
        state=started
      when:
        ansible_os_family == "Debian"

#    - name: Set MySQL root password before installing
#      debconf: name=mysql-server  question=mysql-server/root_password value=1234 vtype=password

#    - name: Confirm MySQL root password before installing
#      debconf: name=mysql-server question=mysql-server/root_password_again value=1234 vtype=password
#      notify:
#      - start mysql

  handlers:
    - name: restart mysql
      service:
        name=mysql
        state=restarted
