---
- name: This is a Play
  hosts: webservers
  remote_user: shk
  become: yes
  gather_facts: no
  vars:
    state: present

  tasks:
    - name: Install Apache
      yum: name=httpd state={{ state }}
      with-items:
        - httpd
      tags:
        - packages

    - template: src=templates/web.conf.j2 dest=/etc/httpd/conf.d/web.conf
      tags:
        - configuration