---
- name: This is a Play
  hosts: all
  remote_user: shk
  become: yes
  gather_facts: no
  #vars:
  #  state: present

  tasks:
    - name: Install Apache
      yum: name={{ package }} state={{ state }}